%if #{>=:#{version},3.3}
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
%endif
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
